#!/usr/bin/env bash
# Manage the manage_my_process process

case "$1" in
  start)
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    $0 stop
    $0 start
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    ;;
esac

